spring:
#  zipkin:
#    base-url: http://localhost:9411
  application:
    name: yjw-config
  boot:
    admin:
      client:
        url: http://localhost:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/yangjunwei1/fileconfig.git
          search-paths: respo
          username: 13621289435@139.com
          password: yjw1985
server:
  port: 8888
eureka:
  instance:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/